#!/bin/sh
PARSE_FILES="$*"
if [ "$PARSE_FILES" = "" ]; then
  PARSE_FILES=*.qs
fi

THISFILE="$0"
readlink "$0" >/dev/null && THISFILE=`readlink "$0"`
THISDIR=`dirname "$THISFILE"`
APPDIR=`dirname "$THISDIR"`
echo "Starting parsers for $PARSE_FILES"
TOTALFILES=""
OKFILES=""

for file in $PARSE_FILES
do
  NAME=`basename $file`
  DIR=`dirname $file`
  echo -n "$DIR Parsing $NAME . . . "
  LOGFILE="$DIR/.parse-$NAME.log"
  python "$APPDIR/flscriptparse.py" $file 2>/dev/null >$LOGFILE
  ERRORCOUNT=`grep "#ERROR#" $LOGFILE | wc -l`
  TOTALFILES+="$file
"
  if [ "$ERRORCOUNT" = "0" ]; then
    echo "done."
    OKFILES+="$file
"
    unlink $LOGFILE
  elif [ "$ERRORCOUNT" = "1" ]; then
    echo -n "$ERRORCOUNT Error found."
    grep "#ERROR#" -B10 -m1 $LOGFILE
  else
    echo -n "$ERRORCOUNT Errors found."
    grep "#ERROR#" -B10 -m1 $LOGFILE
  fi
done
OKFILES="`echo -n "$OKFILES" | wc -l`"
TOTALFILES="`echo -n "$TOTALFILES" | wc -l`"

echo "$OKFILES of $TOTALFILES files parsed correctly"